[CS-M-035] android: Form main screen with navigation
Aleksio02/CFUVScheduling pull request #74
Opened 2024-04-19 15:40 UTC by SanyaPilot

Видео в телеге)

2024-04-20 21:26 UTC, Aleksio02 requested changes
Выводи не "Четная/нечетная неделя", а конкретную дату.

Мб при нажатии на группу автоматически переходить на страницу расписания?

2024-04-22 05:00 UTC, SanyaPilot commented
Так это просто панель навигации и топ бар, поведение отдельных экранов не входит в этот pull request

2024-04-22 05:02 UTC, SanyaPilot commented
Так это просто панель навигации и топ бар, поведение отдельных экранов не входит в этот pull request
Про переход на страницу расписания уже обсуждали, как по мне абсолютно ненужный функционал

2024-04-22 05:33 UTC, Aleksio02 approved these changes

2024-04-22 05:34 UTC, merged